### PR TITLE
pip installation support

### PR DESCRIPTION
**Pull request by tudoroancea**
Hi there! After seeing issues like [this one](https://github.com/pnnl/neuromancer/issues/7) and after myself wanting to install neuromancer via pip, I started implementing more thorough `setup.py` and `requirements.txt` files.
I also added CI tests that pass most of the tests with pytest.

### CODE REVIEW

**Comment by tudoroancea** [comment]
We could introduce a more comprehensive build matrix to test several OS platforms and versions:
```yaml
os: [ "ubuntu-22.04", "ubuntu-20.04", "windows-2022", "windows-2019", "macos-12", "macos-11" ]
```
as well as CPU/CUDA versions of pytorch

**Comment by clegaard** [comment]
I am working on something similar too, see https://github.com/pnnl/neuromancer/issues/7#issuecomment-1440381844

**Review by aaron-tuor — COMMENTED** [review]
Work from this pull request was incorporated into an earlier merged pull request.

**Comment by aarontuor** [comment]
Some of this work was incorporated in an earlier merge

**Pull request closed without merging**
