### PR TITLE
Feature/adding examples of DeepONets

### PR DESCRIPTION
**Pull request by brunopjacob**

### CODE REVIEW

**Comment by colby-ham** [comment]
Antiderivative Operator - Aligned Dataset tutorial notebook complete, tested on collaboratory

**Comment by RBirmiwal** [comment]
Some general comments: 

The notebook is the main entry point for this feature from our end-users so I will start from there and work backwards: 

It seems like the notebook is based off the DeepXDE / Jax notebooks for learning the anti-derivative operator. I want our Neuromancer notebook to be better than theirs w.r.t: 

- Being educational. Why are DeepONets of interest anyway? What is their relationship to existing methods in our library such as PINNs and Deep Koopman Operators? What is operator-theoretic learning and why might that be useful? What is the universal approximation theorem for operators (as opposed to functions) and why is that important? I found the paper and this video helpful for me: https://www.youtube.com/watch?v=1bS0q0RkoH0. 
- Being educational part 2, compare and contrast: 
-- As Neuromancer builds out its methods capabilities, I would like to see emphasis placed on where/how a new method being implemented (in this case Deep Operator Networks) is related (unrelated) to the existing universe of methods we have implemented. I understand this might take more involved understanding of operator theory and DeepONets themselves. 
-- Can we use DeepONets to learn nonlinear system dynamics found in some of our NODE / PINN examples? Likewise what are other methods out there for learning operators? 

The above discussion points can be elaborated in the notebook as well as the supporting README. 

- User-friendliness and modularity: Consider our Deep Koopman operator notebook. I like how it consists of two MLP blocks and a Koopman operator. The composite of these "nodes" then becomes the deep koopman operator. As a result the Deep Koopman Operator as a network has been "opened up" to its most modular components, but not so much as to confuse the user. Can we do something similar for the DeepONet? I don't believe it's entirely necessary for the DeepONet to be it's own separate block. The blocks in blocks.py are meant to be quite atomic and pluggable into multiple use-cases. Thus I am not certain that it belongs as its own block rather than a composite of truly atomic blocks. 

- DeepONets + Control: This is especially true if we wish to provide additional constraints on the trunk and / or branch networks. For example consider this paper https://arxiv.org/pdf/2309.07899. Without looking at it in too much detail, do we think we canimplement parts of it in our Neuromancer DeepONet version using our symbolic language? 

With the current state of the notebook I am not satisfied to approve this PR. I'd like all future notebooks to be bar-raisers above our peers. Thus in terms of action items; 
1. Add some educational / tutorial-like elements touching on the points above. 
2. W.r.t having its own blocks.py class, or having it as a composite as in the Deep Koopman Operator notebook, I am biased towards the latter, especially considering the future possibility of distinct control schemes on the trunk and or branch, as well as keeping a consistent format. But we can have a discussion on this if the DeepONet can be plugged-in to multiple use-cases just like an MLP or RNN can. 

We can have a meeting next week to discuss a bit more after these action items have been implemented. If possible I'd like a prototype notebook showcasing point (2) where the DeepONet is a composition of (MLP blocks to weigh pros and cons. 

Thanks

**Comment by RBirmiwal** [comment]
FYI I am still reviewing all the code and some of my points might be already complete. For example I see the composite notebook prototype here: 

https://github.com/pnnl/neuromancer/blob/a0a0412b7e1b10c47a324b9684ca9597a43fe9fc/examples/DeepONets/antiderivative_aligned_multi_node.ipynb

Is there a reason this was removed?

**Review by drgona — COMMENTED** [review]
Lets make the DeepOnet class more modular by allowing branch and trunk nets to be parametrized by arbitrary blocks.
We don't need to inherit from Block class, lets make it nn.Module with two positional arguments in the forward pass (trunk_inputs, branch_inputs)

We agreed to create a new file operators.py in dynamics directory - where we will keep neural operator approaches.

Also, let's think about naming our directories in examples. Currently, we have ODEs and PDEs focusing on problem type. If we are to keep this then lets move the neural operator examples to corresponding ODEs or PDEs directory based on problem type solved. If we want to keep neural operators all in one directory we should call it neural_operators instead DeepOnets. In this case we can also think to rename PDEs to PINNs.

**Comment by drgona** [comment]
something is wrong with this PR, check your local branch, it shows 500 commits and 287 changes files

**Comment by colby-ham** [comment]
Originally this was a branch from master, I attempted to rebase onto develop but there may have been some mistakes. If the commit history is important I can create a new branch with the current state to be more succinct.

**Comment by colby-ham** [comment]
My bad on the messy rebase, I updated file state from a new branch feature/neural_operators to minimize changes and started a new pr https://github.com/pnnl/neuromancer/pull/168

**Pull request closed without merging**
